"""Train and score a provisional NER model on AI silver labels only."""
from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import spacy
from spacy.training import Example
from spacy.util import fix_random_seed


def load(path):
    return [json.loads(line) for line in path.open()]

def example(nlp, row):
    doc = nlp.make_doc(row["clean_text"])
    return Example.from_dict(doc, {"entities": [(e["evidence_start"], e["evidence_end"], e["label"]) for e in row["entities"]]})

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", type=Path, default=Path("data/annotations/ai_annotated.jsonl"))
    p.add_argument("--model-dir", type=Path, default=Path("models/silver-ner-v1"))
    p.add_argument("--report", type=Path, default=Path("reports/silver_ner_evaluation.json"))
    p.add_argument("--epochs", type=int, default=18)
    a = p.parse_args()
    if a.model_dir.exists() or a.report.exists(): p.error("refusing to overwrite immutable provisional model artifacts")
    rows = load(a.input)
    if any(r.get("annotation_source") != "ai" or r.get("annotation_status") != "ai_annotated" or r.get("label_origin") != "silver" for r in rows): p.error("input must contain only ai_annotated silver labels")
    splits = {name: [row for row in rows if row["split"] == name] for name in ("train", "validation", "test")}
    if {name: len(values) for name, values in splits.items()} != {"train": 200, "validation": 50, "test": 75}: p.error("expected fixed 200/50/75 split allocation")
    fix_random_seed(17); random.seed(17)
    nlp = spacy.blank("en"); ner = nlp.add_pipe("ner")
    for row in splits["train"]:
        for entity in row["entities"]: ner.add_label(entity["label"])
    train = [example(nlp, row) for row in splits["train"]]
    optimizer = nlp.initialize(lambda: train)
    for _ in range(a.epochs):
        random.shuffle(train)
        for batch in spacy.util.minibatch(train, size=8): nlp.update(batch, sgd=optimizer, drop=0.25)
    def score(rows):
        predicted = []
        gold = []
        for row in rows:
            predicted.extend((ent.start_char, ent.end_char, ent.label_) for ent in nlp(row["clean_text"]).ents)
            gold.extend((ent["evidence_start"], ent["evidence_end"], ent["label"]) for ent in row["entities"])
        # Per-document identity prevents equal offsets in separate narratives from matching.
        predicted, gold = set(), set()
        for index, row in enumerate(rows):
            predicted |= {(index, ent.start_char, ent.end_char, ent.label_) for ent in nlp(row["clean_text"]).ents}
            gold |= {(index, ent["evidence_start"], ent["evidence_end"], ent["label"]) for ent in row["entities"]}
        correct = len(predicted & gold); precision = correct / len(predicted) if predicted else 0; recall = correct / len(gold) if gold else 0
        return {"records": len(rows), "predicted_entities": len(predicted), "gold_silver_entities": len(gold), "exact_precision": precision, "exact_recall": recall, "exact_f1": 2*precision*recall/(precision+recall) if precision+recall else 0}
    validation, test = score(splits["validation"]), score(splits["test"])
    a.model_dir.mkdir(parents=True); nlp.to_disk(a.model_dir)
    report = {"experiment": "silver-ner-v1", "metric_scope": "Silver-label evaluation only; not human-validated performance, gold evaluation, calibration, or domain-generalization evidence.", "training": {"records": 200, "epochs": a.epochs, "seed": 17, "labels": sorted(ner.labels)}, "validation": validation, "test": test, "limitations": ["Targets were generated by deterministic rules.", "Test labels share the same silver-generation process as training labels.", "Human privacy review, double annotation, adjudication, gold NER evaluation, and external-domain evaluation remain required."]}
    a.report.parent.mkdir(parents=True, exist_ok=True); a.report.write_text(json.dumps(report, indent=2)+"\n")
    print(json.dumps({"validation_silver_exact_f1": validation["exact_f1"], "test_silver_exact_f1": test["exact_f1"], "scope": "silver-label evaluation only"}, indent=2))
if __name__ == "__main__": main()
